/**
 * Waypoint build metadata — generated by scripts/generate-build-info.mjs
 * Do not edit manually.
 */
(function (global) {
  "use strict";
  var BUILD = {
  "commit": "cf51ce4",
  "commitFull": "cf51ce49f1152aade6346968d94aba3b04d6ea17",
  "deployedAt": "2026-07-10T02:02:47.368Z",
  "locationSchema": 3,
  "loaderVersion": 2
};
  var scriptLoads = [];

  function getVersionQuery() {
    return BUILD && BUILD.commit ? "?v=" + BUILD.commit : "";
  }

  function trackScript(scriptEl) {
    if (!scriptEl || !scriptEl.src) return;
    var entry = {
      url: scriptEl.src,
      startedAt: new Date().toISOString(),
      status: "pending",
      cacheSource: "network"
    };
    scriptLoads.push(entry);
    scriptEl.addEventListener("load", function () {
      entry.status = "loaded";
      entry.loadedAt = new Date().toISOString();
    });
    scriptEl.addEventListener("error", function () {
      entry.status = "error";
      entry.loadedAt = new Date().toISOString();
    });
  }

  function expose() {
    global.__WAYPOINT_BUILD__ = {
      commit: BUILD.commit,
      commitFull: BUILD.commitFull,
      deployedAt: BUILD.deployedAt,
      locationSchema: BUILD.locationSchema,
      loaderVersion: BUILD.loaderVersion
    };
    global.WDS = global.WDS || {};
    global.WDS.build = {
      info: BUILD,
      getVersionQuery: getVersionQuery,
      trackScript: trackScript,
      getScriptLoads: function () { return scriptLoads.slice(); }
    };
  }

  expose();
})(typeof window !== "undefined" ? window : globalThis);
