/**
 * Waypoint build metadata — generated by scripts/inject-build-metadata.mjs
 * Do not edit manually. Production values come from GITHUB_SHA at deploy time.
 */
(function (global) {
  "use strict";
  var BUILD = {
  "commit": "local",
  "commitFull": "local",
  "deployedAt": "2026-07-12T21:30:51.516Z",
  "locationSchema": 4,
  "loaderVersion": 2,
  "migrationEpoch": 3,
  "minRecoveryBuild": "cf51ce4",
  "shortCommit": "local",
  "builtAt": "2026-07-12T21:30:51.516Z",
  "workflowRunId": null,
  "source": "source-tree"
};
  var scriptLoads = [];

  function getVersionQuery() {
    return BUILD && BUILD.commit ? "?v=" + BUILD.commit : "";
  }

  function trackScript(scriptEl) {
    if (!scriptEl || !scriptEl.src) return;
    var entry = {
      url: scriptEl.src,
      startedAt: new Date().toISOString(),
      status: "pending",
      cacheSource: "network"
    };
    scriptLoads.push(entry);
    scriptEl.addEventListener("load", function () {
      entry.status = "loaded";
      entry.loadedAt = new Date().toISOString();
    });
    scriptEl.addEventListener("error", function () {
      entry.status = "error";
      entry.loadedAt = new Date().toISOString();
    });
  }

  global.__WAYPOINT_BUILD__ = {
    commit: BUILD.commit,
    commitFull: BUILD.commitFull,
    shortCommit: BUILD.shortCommit,
    deployedAt: BUILD.deployedAt,
    builtAt: BUILD.builtAt,
    workflowRunId: BUILD.workflowRunId,
    source: BUILD.source,
    locationSchema: BUILD.locationSchema,
    loaderVersion: BUILD.loaderVersion,
    migrationEpoch: BUILD.migrationEpoch,
    minRecoveryBuild: BUILD.minRecoveryBuild
  };
  global.WDS = global.WDS || {};
  global.WDS.build = {
    info: BUILD,
    getVersionQuery: getVersionQuery,
    trackScript: trackScript,
    getScriptLoads: function () { return scriptLoads.slice(); }
  };
})(typeof window !== "undefined" ? window : global);
